name: 🐛 Bug Report
description: Found a bug? Help us squash it.
labels: ["bug"]

body:

- type: markdown
  attributes:
    value: |
      Please we aware that Helium is free and is not under active development. Though [supporting the project financially](https://github.com/sponsors/alexdlaird) is appreciated ❤️ (since Helium has operating costs, even though it is free to use), we make no guarantees bug reports will be looked at or considered.

      Though this project is not under active development, we are still happy to review pull requests submitted by the community to resolve bugs, so submitting a report of your experience may still be helpful to us and others.

- type: checkboxes
  id: ack
  attributes:
    label: Acknowledgements
    options:
    - label: I have written a descriptive issue title
      required: true
    - label: I have searched [Issues](issues?q=is%3Aissue) to see if the bug has already been reported
      required: true
    - label: I have searched [Stack Overflow](https://stackoverflow.com/questions/) to ensure the issue I'm experiencing has not already been discussed

- type: input
  id: os-version
  attributes:
    label: Operating System
    placeholder: macOS 10.14.5
  validations:
    required: true

- type: input
  id: sdk-version
  attributes:
    label: SDK Version
    placeholder: Python 3.9.2

- type: input
  id: library-version
  attributes:
    label: Library Version
    placeholder: pyngrok 1.0.3

- type: textarea
  id: describe-the-bug
  attributes:
    label: Describe the Bug
    description: A clear and concise description of what the bug is, including exceptions thrown.
  validations:
    required: true

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to Reproduce
    description: A snippet of the code used to reproduce the behavior.
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: A brief description of what you expected to happen.
