name: Validate

on:
  workflow_call:


jobs:
  validate:
    name: Validate

    env:
      FORCE_COLOR: 1
      PYTHONDONTWRITEBYTECODE: 1

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.8", "3.9", "3.11" ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build test coverage
        run: make install test
      - name: Check code
        run: make check
      - name: Validate package
        run: make local
      - name: Upload test coverage
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/coverage
      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/test-results